import type { NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import styles from "../../public/styles/Home.module.css";

const schema = yup
	.object({
		username: yup.string().max(40, "Max 10 Character").trim().required(),
		email: yup
			.string()
			.email("enter a valid email address")
			.trim()
			.required(),
		address: yup.string().trim().required(),
		password: yup.string().trim().required(),
	})
	.required();

const Home: NextPage = () => {
	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm({
		resolver: yupResolver(schema),
	});

	const onSubmit = (data: any) => console.log(data);

	return (
		<div>
			<Head>
				<title>Form Validation</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.container}>
				<h2>Form validation with react-hook-form and yup</h2>
				<form action="" onSubmit={handleSubmit(onSubmit)}>
					<div className={styles.formGroup}>
						<label htmlFor="username">Username</label>
						<input type="text" id="username" {...register("username")} />
						<small style={{ color: "red" }}>
							{errors.username?.message}
						</small>
					</div>
					<div className={styles.formGroup}>
						<label htmlFor="email">Email</label>
						<input type="text" id="email" {...register("email")} />
						<small style={{ color: "red" }}>
							{errors.email?.message}
						</small>
					</div>
					<div className={styles.formGroup}>
						<label htmlFor="address">Address</label>
						<input type="text" id="address" {...register("address")} />
						<small style={{ color: "red" }}>
							{errors.address?.message}
						</small>
					</div>
					<div className={styles.formGroup}>
						<label htmlFor="password">Password</label>
						<input
							type="password"
							id="password"
							{...register("password")}
						/>
						<small style={{ color: "red" }}>
							{errors.password?.message}
						</small>
					</div>
					<button type="submit" style={{ marginBottom: "20px" }}>
						Submit
					</button>
				</form>
			</main>
		</div>
	);
};

export default Home;
